excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://Divye7.github.io
title: JEWELRIFY
email: divye.kapoor@ymail.com
author: Divye Kapoor
description: Hi. I am Divye, proud founder of JEWELRIFY, fashion jewellery startup based out of Delhi.
paginate: 3
google_analytics: 